display:
  default:
    display_title: Master
    display_options:
      fields:
        info:
          label: 'وصف الصندوق'
        type:
          label: 'نوع الصندوق'
        changed:
          label: Changed
        operations:
          label: عمليات
      filters:
        info:
          expose:
            label: 'وصف الصندوق'
        type:
          expose:
            label: 'نوع الصندوق'
