label: Files
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- All -'
      fields:
        filename:
          label: Name
        filemime:
          label: 'MIME type'
        filesize:
          label: Size
        status:
          label: Status
        count:
          label: 'Used in'
      filters:
        filename:
          expose:
            label: Filename
        filemime:
          expose:
            label: 'MIME type'
        status:
          expose:
            label: Status
      title: Files
  page_1:
    display_options:
      menu:
        title: Files
  page_2:
    display_options:
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- All -'
      fields:
        entity_label:
          label: Entity
        type:
          label: 'Entity type'
      arguments:
        fid:
          exception:
            title: All
