display:
  default:
    display_title: Master
    display_options:
      fields:
        name:
          label: 'اسم المستخدم'
        status:
          label: الحالة
          settings:
            format_custom_true: نشط
        roles_target_id:
          label: الأدوار
        access:
          label: 'Last access'
        operations:
          label: عمليات
      exposed_form:
        options:
          submit_button: انتقاء
      filters:
        status:
          group_info:
            label: الحالة
            group_items:
              1:
                title: نشط
  page_1:
    display_options:
      menu:
        title: لائحة
