display:
  default:
    display_title: Master
    display_options:
      fields:
        filename:
          label: الاسم
        status:
          label: الحالة
      exposed_form:
        options:
          submit_button: انتقاء
      filters:
        status:
          expose:
            label: الحالة
  page_2:
    display_options:
      fields:
        entity_label:
          label: الكيان
