display:
  default:
    display_title: Master
    display_options:
      fields:
        filename:
          label: الاسم
        status:
          label: الحالة
      filters:
        status:
          expose:
            label: الحالة
