display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: انتقاء
      fields:
        media_bulk_form:
          action_title: إجراء
        bundle:
          label: 'Media type'
        status:
          label: الحالة
          settings:
            format_custom_true: 'تم النشر'
        changed:
          label: Changed
        operations:
          label: عمليات
      filters:
        bundle:
          expose:
            label: 'Media type'
        status:
          group_info:
            group_items:
              1:
                title: 'تم النشر'
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
