display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: انتقاء
      fields:
        filename:
          label: الاسم
        status:
          label: الحالة
      filters:
        status:
          expose:
            label: الحالة
