display:
  default:
    display_options:
      fields:
        status:
          label: الحالة
          settings:
            format_custom_true: نشط
      filters:
        status:
          group_info:
            label: الحالة
            group_items:
              1:
                title: نشط
