label: Media
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- All -'
      fields:
        thumbnail__target_id:
          label: Thumbnail
        bundle:
          label: 'Media type'
        uid:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: 'تم النشر'
        changed:
          label: Changed
        operations:
          label: Operations
      filters:
        bundle:
          expose:
            label: 'Media type'
        status:
          expose:
            label: 'True'
          group_info:
            group_items:
              1:
                title: 'تم النشر'
        langcode:
          expose:
            label: Language
      title: Media
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
