display:
  default:
    display_title: Master
    display_options:
      fields:
        media_bulk_form:
          action_title: إجراء
      filters:
        status:
          group_info:
            label: 'تم النشر'
            group_items:
              1:
                title: 'تم النشر'
        name:
          expose:
            label: الاسم
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
  page:
    display_options:
      fields:
        media_bulk_form:
          action_title: إجراء
        edit_media:
          text: تحرير
        delete_media:
          text: حذف
  widget:
    display_options:
      filters:
        name:
          expose:
            label: الاسم
  widget_table:
    display_options:
      fields:
        name:
          label: الاسم
        changed:
          label: Changed
      filters:
        name:
          expose:
            label: الاسم
