display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- All -'
      filters:
        status:
          group_info:
            label: 'تم النشر'
            group_items:
              1:
                title: 'تم النشر'
        name:
          expose:
            label: Name
        langcode:
          expose:
            label: Language
      title: Media
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
  page:
    display_options:
      fields:
        edit_media:
          text: Edit
        delete_media:
          text: Delete
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Changed
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
