display:
  default:
    display_options:
      fields:
        bundle:
          label: 'Media type'
        status:
          settings:
            format_custom_true: 'تم النشر'
        changed:
          label: Changed
      filters:
        bundle:
          expose:
            label: 'Media type'
        status:
          group_info:
            group_items:
              1:
                title: 'تم النشر'
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
