display:
  default:
    display_title: الرئيسي
    display_options:
      exposed_form:
        options:
          submit_button: تطبيق
          reset_button_label: 'إعادة الضبط'
          exposed_sorts_label: 'الترتيب حسب'
          sort_asc_label: تصاعدي
          sort_desc_label: تنازلي
      pager:
        options:
          expose:
            items_per_page_options_all_label: '- الكل -'
            offset_label: الإزاحة
          tags:
            previous: '‹ السابقة'
            next: 'التالية ›'
            first: '« الأولى'
            last: 'الأخيرة »'
      fields:
        sensor_status:
          label: الحالة
        sensor_message:
          label: 'رسالة الحالة'
        timestamp:
          label: 'التوقيت الزمني'
      title: السجل
      arguments:
        sensor_name:
          exception:
            title: الكل
  detail_page_log:
    display_options:
      fields:
        timestamp:
          label: 'التوقيت الزمني'
        sensor_status:
          label: الحالة
        sensor_message:
          label: 'رسالة الحالة'
  page_1:
    display_title: الصفحة
    display_options:
      menu:
        title: السجل
