display:
  default:
    display_options:
      fields:
        status:
          settings:
            format_custom_true: 'تم النشر'
        changed:
          label: Changed
      filters:
        status:
          group_info:
            group_items:
              1:
                title: 'تم النشر'
