dist: trusty
language: php
cache:
  - composer

# addons:
#   chrome: stable

php:
  - 7.2

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='8.x'
     - DRUSH_VERSION='8.*'
     - PHPCS_VERSION='2.9.*@dev'
     - CODER_VERSION='dev-8.x-2.x'
     - DB=sqlite

before_script:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Composerify.
  - composer install

  # Whereever you go, there you are.
  - cd $TRAVIS_BUILD_DIR

script:
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  - ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom
  - test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom

after_success:
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
