dist: bionic
language: php
cache:
  - composer

addons:
  chrome: stable
  hosts:
    - localhost

php:
  - 7.3

services:
  - mysql

env:
  global:
     - DRUPAL_REPO='git://drupalcode.org/project/drupal.git'
     - DRUPAL_VERSION='8.x'
     - DRUSH_VERSION='8.*'
     - PHPCS_VERSION='2.9.*@dev'
     - CODER_VERSION='dev-8.x-2.x'
     - DB=sqlite
     - COMPOSER_MEMORY_LIMIT=-1

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update --1

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # Composerify.
  - composer install

  # Need to work out updates that work with composer v2, since the lock file is outdated.
  - composer update

  # Nodify.
  - npm i

  # Set up database access.
  - mysql -e "CREATE DATABASE drupal;"
  - mysql -e "GRANT ALL ON drupal.* to drupal@127.0.0.1 IDENTIFIED BY 'drupal';"

  # Whereever you go, there you are.
  - cd $TRAVIS_BUILD_DIR

script:
  # PHP Lint.
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  # PHPCS.
  - ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom
  - test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom

  # Theme build.
  - composer run sass

  # Install Drupal and import config.
  - cd ${TRAVIS_BUILD_DIR}/html
  - ../vendor/bin/drush -y si --db-url=mysql://drupal:drupal@127.0.0.1/drupal minimal
  - ../vendor/bin/drush -y cset system.site uuid $(grep uuid ${TRAVIS_BUILD_DIR}/config/system.site.yml | awk '{print $2}')
  - ../vendor/bin/drush -y cim --source=${TRAVIS_BUILD_DIR}/config

  # Run a simple drush based web server.
  - ../vendor/bin/drush rs 127.0.0.1:8080 >/dev/null 2>&1 &
  - ../vendor/bin/drush php-eval 'node_access_rebuild();'
  - ../vendor/bin/drush cr

  # Run e2e tests.
  - composer run e2e

after_success:
  - cd $TRAVIS_BUILD_DIR
  - npm run pwmetrics -- http://127.0.0.1:8080
  - killall -9 php
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
