dist: focal
language: php
cache:
  - composer

php:
  - 8.0

# Make sure we have a recent version of docker-compose and chrome.
addons:
  apt:
    packages:
      - docker-compose
  chrome: stable
  hosts:
    - localhost

services:
  - mysql

env:
  global:
    - NODE_ENV=travis

before_script:
  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Ensure the PHP environment is ready.
  - phpenv rehash

  # You *will* use HTTPS.
  - composer config --global github-protocols https
  
  # Composerify.
  - composer install

  # Set up database access.
  - mysql -e "CREATE DATABASE drupal;"
  - mysql -e "CREATE USER drupal@127.0.0.1 IDENTIFIED BY 'drupal';"
  - mysql -e "GRANT ALL ON drupal.* to drupal@127.0.0.1;"

  # Wherever you go, there you are.
  - cd $TRAVIS_BUILD_DIR

script:
  # PHP Lint.
  - test ! -d ./html/modules/custom || find -L ./html/modules/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l
  - test ! -d ./html/themes/custom || find -L ./html/themes/custom -iregex '.*\.\(php\|module\|inc\|install\)$' -print0 | xargs -0 -n 1 -P 4 php -l

  # PHPCS.
  - test ! -d ./html/modules/custom || ./vendor/bin/phpcs -p --report=full ./html/modules/custom
  - test ! -d ./html/themes/custom || ./vendor/bin/phpcs -p --report=full ./html/themes/custom

  # Install Drupal and import config.
  - cd ${TRAVIS_BUILD_DIR}/html
  - ../vendor/bin/drush -y si --db-url=mysql://drupal:drupal@127.0.0.1/drupal minimal
  - ../vendor/bin/drush -y cset system.site uuid $(grep uuid ${TRAVIS_BUILD_DIR}/config/system.site.yml | awk '{print $2}')
  - zcat ${TRAVIS_BUILD_DIR}/html/sites/default/sample_data/sample.sql.gz | ../vendor/bin/drush -y sqlc
  - ../vendor/bin/drush -y cim --source=${TRAVIS_BUILD_DIR}/config

  # Run a simple drush based web server.
  - ../vendor/bin/drush rs 127.0.0.1:8080 >/dev/null 2>&1 &
  - ../vendor/bin/drush php-eval 'node_access_rebuild();'
  - ../vendor/bin/drush cr

  # Run e2e tests.
  - cd $TRAVIS_BUILD_DIR
  - composer run e2e

after_success:
  - killall -9 php
  - echo "The tests completed without errors."

after_failure:
  - echo "The tests failed. Please check the output above for problems."
