ocha_gtm.settings:
  type: config_object
  label: 'OCHA GTM Settings'
  mapping:
    container_id:
      type: string
      label: 'GTM Container ID'
    environment_id:
      type: string
      label: 'Environment ID'
    environment_token:
      type: string
      label: 'Environment token'
