display:
  default:
    display_title: Основной
    display_options:
      exposed_form:
        options:
          submit_button: Применить
          reset_button_label: Сбросить
          exposed_sorts_label: 'Сортировать по'
          sort_asc_label: 'По возрастанию'
          sort_desc_label: 'По убыванию'
      pager:
        options:
          expose:
            items_per_page_label: 'Элементов на страницу'
            items_per_page_options_all_label: '- Все -'
            offset_label: Пропустить
          tags:
            previous: '‹ предыдущая'
            next: 'следующая ›'
            first: '« первая'
            last: 'последняя »'
      fields:
        sensor_status:
          label: Статус
        sensor_message:
          label: Статус
        execution_time:
          label: 'Время исполнения'
        timestamp:
          label: Время
      title: Журнал
      arguments:
        sensor_name:
          exception:
            title: Все
  detail_page_log:
    display_options:
      fields:
        timestamp:
          label: Время
        sensor_status:
          label: Статус
        sensor_message:
          label: Статус
        execution_time:
          label: 'Время исполнения'
  page_1:
    display_title: Страница
    display_options:
      menu:
        title: Журнал
