display:
  default:
    display_title: Master
    display_options:
      fields:
        bundle:
          label: Type
        status:
          label: Status
      filters:
        bundle:
          expose:
            label: Type
