display:
  default:
    display_title: Master
    display_options:
      fields:
        status:
          label: Status
      filters:
        status:
          group_info:
            label: Status
