label: 'Biblioteca de medios'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: 'Apply filters'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        media_bulk_form:
          action_title: Action
      filters:
        status:
          expose:
            label: 'Publishing status'
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
              2:
                title: Unpublished
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: 'Media type'
          group_info:
            label: 'Media type'
        langcode:
          expose:
            label: Language
      sorts:
        created:
          expose:
            label: 'Newest first'
        name:
          expose:
            label: 'Name (A-Z)'
        name_1:
          expose:
            label: 'Name (Z-A)'
      title: Media
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
  page:
    display_title: Page
    display_options:
      fields:
        media_bulk_form:
          action_title: Action
        edit_media:
          alter:
            text: 'Edit {{ name }}'
            alt: 'Edit {{ name }}'
          text: Edit
        delete_media:
          alter:
            text: 'Delete {{ name }}'
            alt: 'Delete {{ name }}'
          text: Delete
  widget:
    display_title: Widget
    display_options:
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
  widget_table:
    display_options:
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: Name
        uid:
          label: Author
        changed:
          label: Changed
      filters:
        name:
          expose:
            label: Name
      arguments:
        bundle:
          exception:
            title: All
      header:
        display_link_grid:
          label: Grid
        display_link_table:
          label: Table
