display:
  default:
    display_title: Master
    display_options:
      fields:
        filename:
          label: Nombre
        status:
          label: Estado
      exposed_form:
        options:
          submit_button: Filtro
      filters:
        status:
          expose:
            label: Estado
