label: 'Librería de bloques personalizada'
description: 'Buscar y gestionar bloques personalizados.'
display:
  default:
    display_options:
      fields:
        info:
          label: 'Descripción del bloque'
        type:
          label: 'Tipo de bloque'
        changed:
          label: Changed
      filters:
        info:
          expose:
            label: 'Descripción del bloque'
        type:
          expose:
            label: 'Tipo de bloque'
      title: 'Librería de bloques personalizada'
      empty:
        area_text_custom:
          content: 'No hay bloques personalizados disponibles.'
  page_1:
    display_options:
      menu:
        title: 'Librería de bloques personalizada'
