label: 'Librería de bloques personalizada'
description: 'Buscar y gestionar bloques personalizados.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        info:
          label: 'Descripción del bloque'
        type:
          label: 'Tipo de bloque'
        changed:
          label: Changed
        operations:
          label: Operations
      filters:
        info:
          expose:
            label: 'Descripción del bloque'
        type:
          expose:
            label: 'Tipo de bloque'
      title: 'Librería de bloques personalizada'
      empty:
        area_text_custom:
          content: 'No hay bloques personalizados disponibles.'
  page_1:
    display_options:
      menu:
        title: 'Librería de bloques personalizada'
