label: 'Recent content'
description: 'Recent content.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      title: 'Recent content'
      empty:
        area_text_custom:
          content: 'No content available.'
      use_more_text: More
  block_1:
    display_title: Block
