display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'último »'
      fields:
        sensor_status:
          label: Estado
        sensor_message:
          label: 'Mensaje de estado'
        execution_time:
          label: 'Tiempo de ejecución'
        timestamp:
          label: 'Sello temporal'
      title: Registro
      arguments:
        sensor_name:
          exception:
            title: Todo(s)
  detail_page_log:
    display_options:
      fields:
        timestamp:
          label: 'Sello temporal'
        sensor_status:
          label: Estado
        sensor_message:
          label: 'Mensaje de estado'
        execution_time:
          label: 'Tiempo de ejecución'
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Registro
