label: 'Biblioteca de medios'
display:
  default:
    display_options:
      filters:
        status:
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
  widget_table:
    display_options:
      fields:
        changed:
          label: Changed
