display:
  default:
    display_title: Master
    display_options:
      fields:
        status:
          label: Estado
          settings:
            format_custom_true: Activo
      filters:
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Activo
