display:
  default:
    display_options:
      fields:
        filename:
          label: Nombre
        status:
          label: Estado
      filters:
        status:
          expose:
            label: Estado
