display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
      fields:
        media_bulk_form:
          action_title: Acción
        bundle:
          label: 'Media type'
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
        changed:
          label: Changed
        operations:
          label: Operaciones
      filters:
        bundle:
          expose:
            label: 'Media type'
        status:
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
