display:
  default:
    display_options:
      fields:
        status:
          settings:
            format_custom_true: Publicado
        changed:
          label: Changed
      filters:
        status:
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
  page_1:
    display_options:
      tab_options:
        description: 'Encuentre y gestione el contenido'
