display:
  default:
    display_options:
      fields:
        bundle:
          label: 'Media type'
        status:
          settings:
            format_custom_true: Publicado
        changed:
          label: Changed
      filters:
        bundle:
          expose:
            label: 'Media type'
        status:
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
