display:
  default:
    display_title: Master
    display_options:
      fields:
        name:
          label: 'Nombre de usuario'
        status:
          label: Estado
          settings:
            format_custom_true: Activo
        access:
          label: 'Last access'
        operations:
          label: Operaciones
      exposed_form:
        options:
          submit_button: Filtro
      filters:
        status:
          group_info:
            label: Estado
            group_items:
              1:
                title: Activo
  page_1:
    display_options:
      menu:
        title: Listado
