label: 'Biblioteca de medios'
display:
  default:
    display_title: Master
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
      filters:
        status:
          group_info:
            label: Publicado
            group_items:
              1:
                title: Publicado
        name:
          expose:
            label: Nombre
  page:
    display_options:
      fields:
        media_bulk_form:
          action_title: Acción
        edit_media:
          text: Editar
        delete_media:
          text: Eliminar
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Nombre
  widget_table:
    display_options:
      fields:
        name:
          label: Nombre
        changed:
          label: Changed
      filters:
        name:
          expose:
            label: Nombre
