display:
  default:
    display_title: Master
    display_options:
      fields:
        type:
          label: 'Tipo de contenido'
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
        changed:
          label: Changed
        operations:
          label: Operaciones
      exposed_form:
        options:
          submit_button: Filtro
      filters:
        type:
          expose:
            label: 'Tipo de contenido'
        status:
          expose:
            label: Estado
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
  page_1:
    display_options:
      tab_options:
        description: 'Encuentre y gestione el contenido'
