display:
  default:
    display_title: Master
    display_options:
      fields:
        status:
          label: État
        operations:
          label: Actions
      exposed_form:
        options:
          submit_button: Filtrer
