display:
  default:
    display_title: Master
    display_options:
      fields:
        name:
          label: 'Nom d''utilisateur'
        status:
          label: État
          settings:
            format_custom_true: Actif
        roles_target_id:
          label: Rôles
        operations:
          label: Actions
      exposed_form:
        options:
          submit_button: Filtrer
      filters:
        status:
          group_info:
            label: État
            group_items:
              1:
                title: Actif
  page_1:
    display_options:
      menu:
        title: Lister
