display:
  default:
    display_title: Master
    display_options:
      fields:
        status:
          label: État
          settings:
            format_custom_true: Actif
      filters:
        status:
          group_info:
            label: État
            group_items:
              1:
                title: Actif
