label: Media
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filter
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        thumbnail__target_id:
          label: Thumbnail
        name:
          label: 'Media name'
        bundle:
          label: 'Media type'
        uid:
          label: Author
        status:
          label: Status
          settings:
            format_custom_true: Publié
            format_custom_false: Unpublished
        changed:
          label: Changed
        operations:
          label: Operations
      filters:
        name:
          expose:
            label: 'Media name'
        bundle:
          expose:
            label: 'Media type'
        status:
          expose:
            label: 'True'
          group_info:
            label: 'Statut de publication'
            group_items:
              1:
                title: Publié
              2:
                title: Unpublished
        langcode:
          expose:
            label: Language
      title: Media
      empty:
        area_text_custom:
          content: 'No [view:title] available.'
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
