display:
  default:
    display_title: Master
    display_options:
      fields:
        filename:
          label: Nom
        status:
          label: État
      filters:
        status:
          expose:
            label: État
