label: 'Bibliothèque de blocs personnalisés'
description: 'Trouver et gérer les blocs personnalisés.'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
      pager:
        options:
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        info:
          label: 'Description du bloc'
        type:
          label: 'Type de bloc'
        changed:
          label: Changed
        operations:
          label: Operations
      filters:
        info:
          expose:
            label: 'Description du bloc'
        type:
          expose:
            label: 'Type de bloc'
      title: 'Bibliothèque de blocs personnalisés'
      empty:
        area_text_custom:
          content: 'Il n''y a pas de bloc personnalisé disponible.'
  page_1:
    display_options:
      menu:
        title: 'Bibliothèque de blocs personnalisés'
