display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
      fields:
        media_bulk_form:
          action_title: Action
        status:
          label: État
        operations:
          label: Actions
