social_auth_hid.settings:
  type: config_object
  label: 'Social Auth Hid settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    base_url:
      type: string
      label: 'HID base URL'
    auto_redirect:
      type: boolean
      label: 'Auto redirect to HID'
    disable_default:
      type: boolean
      label: 'Disable default user login and reset forms'
    disable_password_fields:
      type: boolean
      label: 'Hide password fields on user edit page'
    disable_email_field:
      type: boolean
      label: 'Disable email field on user edit page'
    disable_user_field:
      type: boolean
      label: 'Disable name field on user edit page'
