social_auth_hid.settings:
  type: config_object
  label: 'Social Auth Hid settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    base_url:
      type: string
      label: 'HID base URL'
