module:
  admin_denied: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  devel: 0
  devel_generate: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  inline_form_errors: 0
  language: 0
  link: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  responsive_image: 0
  search: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  syslog: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  common_design: 0
  claro: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
