_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_denied: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  config_split: 0
  contextual: 0
  datetime: 0
  datetime_range: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facets: 0
  facets_summary: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  image: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  ocha_integrations: 0
  ocha_media_content: 0
  ocha_security: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pwa: 0
  pwa_extras: 0
  responsive_image: 0
  search: 0
  search_api: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  seckit: 0
  select_a11y: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  theme_switcher: 0
  toolbar: 0
  update: 0
  user: 0
  user_expire: 0
  viewsreference: 0
  menu_link_content: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  common_design: 0
  claro: 0
  common_design_subtheme: 0
profile: minimal
