module:
  admin_denied: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  config: 0
  dynamic_page_cache: 0
  field: 0
  file: 0
  filter: 0
  inline_form_errors: 0
  node: 0
  page_cache: 0
  path: 0
  path_alias: 0
  syslog: 0
  system: 0
  text: 0
  toolbar: 0
  update: 0
  user: 0
  minimal: 1000
theme:
  stable: 0
  classy: 0
  common_design: 0
  claro: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
