_core:
  default_config_hash: yOPH6uEZYRHbg2OFP-bze0jGr06fI-Gr_66W-vA8Faw
report-only:
  enable: true
  directives:
    connect-src:
      base: self
      sources:
        - fonts.gstatic.com
        - fonts.googleapis.com
        - 'https://*.google-analytics.com'
        - 'https://analytics.google.com'
        - 'https://*.analytics.google.com'
        - 'https://*.googletagmanager.com'
        - cdn.jsdelivr.net
        - gov-bam.nr-data.net
        - '*.newrelic.com'
        - '*.placeholder.com'
    font-src:
      base: self
      sources:
        - fonts.gstatic.com
        - web.brand.unocha.org
    img-src:
      base: self
      sources:
        - 'data:'
        - '*.placeholder.com'
        - 'https://*.google-analytics.com'
        - 'https://*.googletagmanager.com'
        - www.gstatic.com
        - via.placeholder.com
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - cdn.jsdelivr.net
        - js-agent.newrelic.com
        - gov-bam.nr-data.net
        - 'https://*.googletagmanager.com'
        - '*.google-analytics.com'
    script-src-attr:
      base: self
    script-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
        - www.gstatic.com
        - www.google.com
        - cdn.jsdelivr.net
        - js-agent.newrelic.com
        - gov-bam.nr-data.net
        - 'https://*.googletagmanager.com'
        - '*.google-analytics.com'
    style-src:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
    style-src-attr:
      base: self
      flags:
        - unsafe-inline
    style-src-elem:
      base: self
      flags:
        - unsafe-inline
      sources:
        - fonts.googleapis.com
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
enforce:
  enable: true
  directives:
    object-src:
      base: none
    frame-ancestors:
      base: self
  reporting:
    plugin: sitelog
