_core:
  default_config_hash: cP1TZQyv1WdET3iepl2QoyOPK7VeO0xHm0lU_FU1Wmc
site_name: 'Common Design Demo'
short_name: CD
description: 'Drupal website demo of OCHA Common Design'
start_url: /home
scope: ''
lang: en
theme_color: '#1f69b3'
background_color: '#ffffff'
display: fullscreen
default_image: '0'
urls_to_cache: "/home\r\n/demo"
urls_to_exclude: "admin/.*\r\nuser/.*"
offline_page: /offline
cache_version: '1'
cross_origin: false
skip_waiting: false
image: /sites/default/files/pwa/android-chrome-512x512.png
image_small: /sites/default/files/pwa/android-chrome-512x512.pngcopy.png
image_very_small: /sites/default/files/pwa/android-chrome-512x512.pngcopy2.png
