_core:
  default_config_hash: cP1TZQyv1WdET3iepl2QoyOPK7VeO0xHm0lU_FU1Wmc
name: 'Common Design Demo'
short_name: CD
description: 'Drupal website demo of OCHA Common Design'
start_url: /home
scope: /
lang: en
dir: auto
orientation: portrait
categories: {  }
theme_color: '#1f69b3'
background_color: '#ffffff'
display: fullscreen
cross_origin: false
image_fid: 4
image_small_fid: 11
image_very_small_fid: 12
manifest_path_mode: all_except_listed
manifest_paths: |-
  /admin
  /admin/*
  /batch
  /node/add*
  /node/*/*