touch_icons:
  touch-icon-default: touch-icon-default
meta_tags:
  meta-capable: meta-capable
  meta-status-bar-style: meta-status-bar-style
color_select: black_translucent
home_screen_icons:
  iphone5-splash: iphone5-splash
  iphone6-splash: iphone6-splash
  iphoneplus-splash: iphoneplus-splash
  iphonex-splash: iphonex-splash
  iphonexr-splash: iphonexr-splash
  iphonexsmax-splash: iphonexsmax-splash
  ipad-splash: ipad-splash
  ipadpro1-splash: ipadpro1-splash
  ipadpro2-splash: ipadpro2-splash
  ipadpro3-splash: ipadpro3-splash
