touch_icons:
  touch-icon-default: '0'
mask_color: '#1f69b3'
meta_tags:
  meta-capable: meta-capable
  meta-status-bar-style: meta-status-bar-style
  meta-app-title: '0'
color_select: black_translucent
home_screen_icons:
  iphone5-splash: '0'
  iphone6-splash: '0'
  iphoneplus-splash: '0'
  iphonex-splash: '0'
  iphonexr-splash: '0'
  iphonexsmax-splash: '0'
  ipad-splash: '0'
  ipadpro1-splash: '0'
  ipadpro2-splash: '0'
  ipadpro3-splash: '0'
