_core:
  default_config_hash: x6bhN6WZwfVUI_LLMvRJIUW_2c26VTaBozbfXmJWmro
seckit_xss:
  csp:
    checkbox: true
    vendor-prefix:
      x: false
      webkit: false
    report-only: true
    default-src: ''
    script-src: '''self'' fonts.googleapis.com www.gstatic.com gov-bam.nr-data.net www.google.com www.google-analytics.com cdn.jsdelivr.net js-agent.newrelic.com'
    object-src: ''
    style-src: ''
    img-src: '''self'' data: via.placeholder.com'
    media-src: ''
    frame-src: ''
    frame-ancestors: ''
    child-src: ''
    font-src: 'fonts.gstatic.com web.brand.unocha.org'
    connect-src: '''self'' www.google-analytics.com cdn.jsdelivr.net *.newrelic.com gov-bam.nr-data.net fonts.gstatic.com fonts.googleapis.com via.placeholder.com'
    report-uri: /report-csp-violation
    upgrade-req: false
    policy-uri: ''
  x_xss:
    seckit_x_xss_option_disable: Disabled
    seckit_x_xss_option_0: '0'
    seckit_x_xss_option_1: 1;
    seckit_x_xss_option_1_block: '1; mode=block'
    select: 0
seckit_csrf:
  origin: false
  origin_whitelist: 'https://fonts.gstatic.com'
seckit_clickjacking:
  js_css_noscript: false
  noscript_message: 'Sorry, you need to enable JavaScript to visit this website.'
  x_frame: '1'
  x_frame_allow_from: ''
seckit_ssl:
  hsts: false
  hsts_subdomains: false
  hsts_max_age: 1000
  hsts_preload: false
seckit_ct:
  expect_ct: false
  max_age: 86400
  report_uri: ''
  enforce: false
seckit_fp:
  feature_policy: false
  feature_policy_policy: ''
seckit_various:
  from_origin: false
  from_origin_destination: same
  referrer_policy: false
  referrer_policy_policy: no-referrer-when-downgrade
  disable_autocomplete: false
