_core:
  default_config_hash: _t9faeey8ijkiUWjKuz8shcOTzmFLyWYpJQpwcaA3XY
client_id: HID_CLIENT_ID_DO_NOT_COMMIT_TO_REPOSITORY
client_secret: HID_CLIENT_ID_DO_NOT_COMMIT_TO_REPOSITORY
base_url: 'https://auth.humanitarian.id'
auto_redirect: true
disable_default: true
disable_password_fields: true
disable_email_field: true
disable_user_field: true
disable_user_create: false
maintenance_access: false
scopes: profile
endpoints: ''
