_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: en
uuid: b9a23d19-b821-4a18-beaf-542829ad87fc
name: 'Common Design Demo'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/5
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
