<?php

/**
 * @file
 * Installs demo content.
 */

/**
 * Implements hook_modules_installed().
 */
function unocha_demo_content_modules_installed($modules) {
  if (!in_array('unocha_demo_content', $modules)) {
    return;
  }

  /** @var \Drupal\node\Entity\Node $node */
  $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
    'uuid' => 'cdc88ae7-354a-49da-8778-aa891d8f1b74',
  ]);
  $node = reset($nodes);

  if ($node) {
    $config = \Drupal::service('config.factory')->getEditable('system.site');
    $config->set('front', 'node/' . $node->id());
    $config->save();

    \Drupal::logger('unocha_demo_content')->info('Homepage set to node/' . $node->id());
  }
  else {
    \Drupal::logger('unocha_demo_content')->error('Unable to set homepage');
  }

}
