paragraphs.behavior.settings.paragraphs_viewmode_behavior:
  type: paragraphs.behavior.settings_base
  label: 'Paragraphs View Mode Settings'
  mapping:
    override_mode:
      type: text
      label: 'Select which view mode to override'
    override_available:
      type: sequence
      label: 'Select which view modes are allowed'
      sequence:
        type: text
        label: 'View Mode'